# Generated by Django 3.1.7 on 2021-05-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210506_1429'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UIList',
        ),
        migrations.AddField(
            model_name='reviewslist',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reviewslist',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
